import { NextRequest, NextResponse } from "next/server";
import { getContractWithDetails } from "@/lib/db/repo";
import { formatDate, formatMoney, titleCase } from "@/lib/utils";

export const runtime = "nodejs";

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  const contract = getContractWithDetails(params.id);
  if (!contract) return NextResponse.json({ error: "Contract not found" }, { status: 404 });

  const md = renderReport(contract);
  const fileName = `${contract.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-executive-report.md`;

  return new NextResponse(md, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="${fileName}"`,
    },
  });
}

function renderReport(c: NonNullable<ReturnType<typeof getContractWithDetails>>): string {
  const lines: string[] = [];
  lines.push(`# Executive Report: ${c.title}`);
  lines.push("");
  lines.push(`_Generated ${formatDate(new Date().toISOString())} by Contract Intelligence Copilot (independent portfolio demo)._`);
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(c.summary.overview);
  lines.push("");
  lines.push("## Key Terms");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|---|---|");
  for (const t of c.summary.keyTerms) lines.push(`| ${t.label} | ${t.value} |`);
  lines.push("");
  lines.push("## Highlights");
  lines.push("");
  for (const h of c.summary.highlights) lines.push(`- ${h}`);
  lines.push("");
  lines.push(`## Risk Findings (${c.risks.length})`);
  lines.push("");
  if (c.risks.length === 0) {
    lines.push("_No material risks were identified._");
  } else {
    for (const r of c.risks) {
      lines.push(`### ${r.title}: ${titleCase(r.severity)}`);
      lines.push("");
      lines.push(r.description);
      lines.push("");
      lines.push(`**Recommendation:** ${r.recommendation}`);
      lines.push("");
    }
  }
  lines.push(`## Obligations (${c.obligations.length})`);
  lines.push("");
  if (c.obligations.length === 0) {
    lines.push("_No tracked obligations._");
  } else {
    lines.push("| Due date | Status | Party | Type | Description |");
    lines.push("|---|---|---|---|---|");
    for (const o of c.obligations) {
      lines.push(`| ${formatDate(o.dueDate)} | ${titleCase(o.status)} | ${titleCase(o.party)} | ${titleCase(o.type)} | ${o.description} |`);
    }
  }
  lines.push("");
  lines.push(`## Approval Status`);
  lines.push("");
  if (c.approvals.length === 0) {
    lines.push("_No approval workflow configured._");
  } else {
    lines.push("| Step | Approver | Role | Status |");
    lines.push("|---|---|---|---|");
    c.approvals.forEach((a, i) => lines.push(`| ${i + 1} | ${a.approverName} | ${titleCase(a.approverRole)} | ${titleCase(a.status)} |`));
  }
  lines.push("");
  lines.push("## Contract Details");
  lines.push("");
  lines.push(`- **Counterparty:** ${c.counterparty}`);
  lines.push(`- **Type:** ${c.type}`);
  lines.push(`- **Status:** ${titleCase(c.status)}`);
  lines.push(`- **Department:** ${c.department}`);
  lines.push(`- **Owner:** ${c.ownerName}`);
  lines.push(`- **Value:** ${formatMoney(c.value, c.currency)}`);
  lines.push(`- **Risk score:** ${c.riskScore}/100`);
  lines.push(`- **Versions on file:** ${c.versions.length}`);
  lines.push("");
  lines.push("---");
  lines.push("_This report was generated by an independent portfolio demo project inspired by the Contract Lifecycle Management (CLM) product category. Not affiliated with Malbek Inc._");

  return lines.join("\n");
}
